### ISSUE TITLE
Axum stop responding after updating to 0.5.0

### ISSUE THREAD

**Issue by HosMercury** [maxcountryman/axum-messages#10]
something weird weird is happening after just updating axum-messages to 0.5.0
axum stop responding to any request
there is no compilation errors .. no tracing
just 500 server err
..

returning to 0.3.0
it works 

tbh i am not using the latest tower sessions

**Comment by HosMercury** [comment]
updated tower-sessions today working

**Comment by ryanmcgrath** [comment]
@maxcountryman I ran into this as well, and while it's kind of user error, it might be helpful to add a `tracing::error!` call in these failure conditions:

https://github.com/maxcountryman/axum-messages/blob/4a1941ddb9007ec2a229f9f7bd8bf982480782e4/src/lib.rs#L340-L344

https://github.com/maxcountryman/axum-messages/blob/4a1941ddb9007ec2a229f9f7bd8bf982480782e4/src/lib.rs#L346-L354

https://github.com/maxcountryman/axum-messages/blob/4a1941ddb9007ec2a229f9f7bd8bf982480782e4/src/lib.rs#L362-L366

Correct me if I'm wrong, but the dependency mismatch would trigger the first block here, wouldn't it? Right now there's no way to know it's hitting that, it's just a blank 500.

**Comment by maxcountryman** [comment]
Ideally the program would fail to compile so we'd know at build time.

That said, I'm not generally opposed to adding more instrumentation.

**Comment by alexniver** [comment]
> Ideally the program would fail to compile so we'd know at build time.
> 
> That said, I'm not generally opposed to adding more instrumentation.

I'm running into this issue too. 

without `.layer(session_layer)`, code will compile, but page only get 500, no error log, this really confusing.

may be add `tracing::error!("can't find messages in session")` good for new user.

**Comment by maxcountryman** [comment]
@alexniver https://github.com/maxcountryman/axum-messages/blob/d6504e1f6421a6786d353e052183e8f9304b9c26/src/lib.rs#L407

However, tracing does require setup so it's not necessarily visible.

**Comment by alexniver** [comment]
> @alexniver
> 
> https://github.com/maxcountryman/axum-messages/blob/d6504e1f6421a6786d353e052183e8f9304b9c26/src/lib.rs#L407
> 
> However, tracing does require setup so it's not necessarily visible.

oh, sorry, my bad
